config/routes.rb
Rails.application.routes.draw do

  root to: 'murmurs#about'

  resources :murmurs do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/murmur.rb
class Murmur < ApplicationRecord
  validates :content, presence: true, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/murmurs_controller.rb
class MurmursController < ApplicationController

  before_action :set_murmur, only:[:show,:edit,:update,:destroy]

  def index
    @murmurs = Murmur.all
  end

  def new
    if params[:back]
      @murmur = Murmur.new(murmur_params)
    else
      @murmur = Murmur.new
    end
  end

  def create
    @murmur = Murmur.new(murmur_params)
    if @murmur.save
      redirect_to murmurs_path, notice: "呟きを投稿しました"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @murmur.update(murmur_params)
      redirect_to murmurs_path, notice: "投稿を編集しました"
    else
      render 'edit'
    end
  end

  def destroy
    @murmur.destroy
    redirect_to murmurs_path, notice:'投稿を削除しました'
  end

  def confirm
    @murmur = Murmur.new(murmur_params)
    render :new if @murmur.invalid?
  end


  private
  def murmur_params
    params.require(:murmur).permit(:content)
  end

  def set_murmur
    @murmur = Murmur.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/murmurs_helper.rb
module MurmursHelper

  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_murmurs_path
    elsif action_name == 'edit'
      murmur_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Achieve</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <header class="header">
        <nav class="navbar navbar-inverse">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
                <span class="sr-only">Bootstrap</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to 'HOME', root_path, class: "navbar-brand" %>
            </div>
            <div id="gnavi" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li>
                  <%= link_to '呟き一覧', murmurs_path %>
                </li>
                <li>
                  <%= link_to '呟く', new_murmur_path %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    </div>



    <%= yield %>
    <footer>
      <p>DIC_Task</p>
    </footer>
  </body>
</html>

app/views/murmurs/_form.html.erb
<%= form_with(model: @murmur, url: choose_new_or_edit, local:true) do |form| %>

<% if @murmur.errors.any? %>
  <div class="error_render">
    <h2><%= @murmur.errors.count %>件のエラーがあります</h2>
    <ul>
      <% @murmur.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="murmur_title">
  <%= form.label :content,name = '本文' %>
  <%= form.text_field :content %>
</div>
<%= form.submit('投稿する') %>
<% end %>

<%= link_to '呟き一覧へ', murmurs_path, class: "btn btn-default" %>

app/views/murmurs/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 mb30">
      <%= image_tag('task.png', :class => "img-responsive")%>
    </div>
    <div class="col-lg-12">
      <p>これはDICのrails課題です。<br>つぶやきを投稿する機能をつけることで、Railsの機能の一端を学ぶことができます。</p>
      <p>これはTwitterのクローンの課題制作です。</p>
    </div>
  </div>
</div>

app/views/murmurs/confirm.html.erb
<h3>以下の内容で、投稿する</h3>
<%= form_with(model: @murmur, url: murmurs_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @murmur.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @murmur, url: new_murmur_path, local: true, method: 'get') do |form| %>
<%= form.hidden_field :content %>
<%= form.submit '戻る', name: 'back' %>
<% end %>

app/views/murmurs/edit.html.erb
<%= form_with(model: @murmur, local:true) do |form| %>

<% if @murmur.errors.any? %>
  <div class="error_render">
    <h2><%= @murmur.errors.count %>件のエラーがあります</h2>
    <ul>
      <% @murmur.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="murmur_title">
  <%= form.label :content,name = '本文' %>
  <%= form.text_field :content %>
</div>
<%= form.submit('投稿する') %>
<% end %>

<%= link_to '呟き一覧へ', murmurs_path, class: "btn btn-default" %>

app/views/murmurs/index.html.erb
<h1>呟き一覧</h1>
<p><%= notice %></p>
<div class="container">
  <div class="row">
    <% @murmurs.each do |murmur| %>
    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
      <span class="content"><%= murmur.content %></span>
      <div>
        <%= link_to '詳細を確認する', murmur_path(murmur.id), class: "btn btn-success" %>
      </div>
      <div class="">
        <%= link_to '投稿を編集する', edit_murmur_path(murmur.id),data: {confirm: '本当に編集しますか?'}, class: "btn btn-warning" %>
      </div>
      <div class="">
        <%= link_to '投稿を削除する', murmur_path(murmur.id), method: :delete, data: {confirm: '本当に削除しますか？'}, class: "btn btn-danger" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-push-3 center-block">
      <%= link_to '呟く', new_murmur_path, class: "btn btn-primary btn-lg btn-block" %>
    </div>
  </div>
</div>

app/views/murmurs/new.html.erb
<h2>呟きを投稿する</h2>

<%= render 'form' %>

app/views/murmurs/show.html.erb
<h1>呟き詳細画面</h1>
<p>
  内容:<%= @murmur.content %>
</p>
<%= link_to '呟き一覧へ', murmurs_path, class: "btn btn-default" %>